packages:
  - apps/*
  - packages/api
  - packages/db

catalog:
  "@biomejs/biome": ^2.3.13
  "@neondatabase/serverless": 0.10.x
  "@t3-oss/env-core": 0.13.8
  "@tanstack/react-query": ^5.90.20
  "@trpc/client": 11.7.2
  "@trpc/server": ^11.7.1
  "@trpc/tanstack-react-query": ^11.7.2
  "@types/pg": 8.15.6
  date-fns: 4.1.0
  dotenv-cli: 6.0.0
  drizzle-orm: 0.44.7
  pg: 8.16.3
  superjson: 2.2.6
  tsup: 8.5.1
  tsx: 4.21.0
  typescript: 5.9.3
  ultracite: 7.1.5
  zod: 4.1.13

onlyBuiltDependencies:
  - "@clerk/shared"
  - "@prisma/client"
  - "@prisma/engines"
  - "@shopify/react-native-skia"
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - prisma
  - utf-8-validate
